"""
Slack Socket Mode integration for POLIS.
"""

from __future__ import annotations

import logging
import re
import threading
import time
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from datetime import datetime, timezone
from infrastructure.config.settings import get_settings

from connectors.slack.models import (
    SlackEvent,
    SlackUser,
    SlackChannel,
    SlackMessage,
)

from connectors.slack.services import SlackService

from domain.reasoning import (
    Question,
)
from engines.slack.services.slack_identity_service import (
    SlackIdentityService,
)
logger = logging.getLogger(__name__)
class SlackSocketMode:
    """
    Slack Socket Mode listener.
    """

    def __init__(
        self,
        slack_service: SlackService,
        reminder_service,
        slack_client,
    ) -> None:

        self._slack_service = slack_service
        self._reminder_service = reminder_service
        self._slack_client = slack_client
        self._identity_service = SlackIdentityService()
        self._settings = get_settings()

        self._app = App(
            token=self._settings.slack_bot_token,
        )

        self._register_handlers()

    def _register_handlers(self) -> None:

        @self._app.event("message")
        def handle_message(event, say, logger):

            # ======================================================
            # Ignore messages generated by bots.
            # ======================================================

            if event.get("bot_id"):
                return

            # ======================================================
            # Ignore Slack message subtypes.
            # ======================================================

            if event.get("subtype"):
                return

            user_id = event.get("user")
            channel_id = event.get("channel")
            text = event.get("text", "")
            ts = event.get("ts")
            thread_ts = event.get("thread_ts")

            if not user_id:
                return

            if not channel_id:
                return

            if not ts:
                return

            # ======================================================
            # Detect whether this message is directed at POLIS.
            # ======================================================

            bot_user_id = self._settings.slack_bot_user_id

            mention_token = f"<@{bot_user_id}>"

            is_polis_question = mention_token in text

            # ======================================================
            # Always ingest the message first.
            #
            # This preserves the existing learning pipeline.
            # ======================================================

            slack_event = SlackEvent(
                user=SlackUser(
                    user_id=user_id,
                ),
                channel=SlackChannel(
                    channel_id=channel_id,
                ),
                message=SlackMessage(
                    text=text,
                    ts=ts,
                    thread_ts=thread_ts,
                ),
            )

            try:

                saved = self._slack_service.ingest(
                    slack_event,
                )

                logger.info(
                    "POLIS processed Slack message: %s",
                    saved.correlation_id.business_id,
                )

            except Exception:

                logger.exception(
                    "POLIS failed to process Slack message",
                )

                return

            # ======================================================
            # If POLIS was not mentioned, learning is complete.
            # Do not reply.
            # ======================================================

            if not is_polis_question:
                return

            # ======================================================
            # Remove the POLIS mention from the question.
            # ======================================================

            question_text = text.replace(
                mention_token,
                "",
            ).strip()

            # ======================================================
            # Stop all active reminders for the requesting user.
            # ======================================================

            if question_text.lower() == "stop":
                stopped_count = self._reminder_service.stop_for_target(
                    user_id,
                )

                say(
                    text=(
                        f"Stopped {stopped_count} active reminder(s)."
                    ),
                    thread_ts=thread_ts or ts,
                )
                return

            # ======================================================
            # Detect explicit reminder commands.
            # ======================================================

            reminder_match = re.match(
                r"^remind\s+(.+?)\s+to\s+(.+)$",
                question_text,
                re.IGNORECASE,
            )

            if reminder_match:
                target_text = reminder_match.group(1).strip()
                task = reminder_match.group(2).strip()
                if target_text.startswith("<@"):
                    mention_match = re.fullmatch(
                        r"<@([A-Z0-9]+)(?:\|[^>]+)?>",
                        target_text,
                    )

                    target_user = None

                    if mention_match:
                        target_user = {
                            "id": mention_match.group(1),
                        }
                else:
                    target_user = self._identity_service.resolve_user(
                        target_text,
                    )

                if target_user is None:
                    say(
                        text=(
                            f"I couldn't unambiguously identify "
                            f"the reminder target '{target_text}'."
                        ),
                        thread_ts=thread_ts or ts,
                    )
                    return

                target_user_id = target_user["id"]
                logger.info(
                    "Reminder command detected: target=%s task=%s",
                    target_text,
                    task,
                )
                reminder = self._reminder_service.create(
                    target_user_id=target_user_id,
                    creator_user_id=user_id,
                    task=task,
                    channel_id=channel_id,
                    source_message_ts=ts,
                    source_thread_ts=thread_ts,
                    timezone_name=self._settings.reminder_timezone,
                    time_1=self._settings.reminder_time_1,
                    time_2=self._settings.reminder_time_2,
                )

                say(
                    text=(
                        f"Reminder created. "
                        f"I'll remind <@{target_user_id}> "
                        f"twice daily about: {reminder.task}"
                    ),
                    thread_ts=thread_ts or ts,
                )
                return
            if not question_text:
                return

            # ======================================================
            # Ask the POLIS cognitive engine.
            # ======================================================

            try:

                question = Question(
                    text=question_text,
                )

                answer = self._slack_service.ask(
                question,
                )

                logger.info(
                    "POLIS answer confidence: %s",
                    answer.confidence,
                )

                # ==================================================
                # Reply in the same thread.
                #
                # If the original message is already in a thread,
                # use its parent thread_ts.
                #
                # Otherwise, the current message becomes the
                # thread parent.
                # ==================================================

                reply_thread_ts = (
                    thread_ts or ts
                )

                say(
                    text=answer.text,
                    thread_ts=reply_thread_ts,
                )

            except Exception:

                logger.exception(
                    "POLIS failed to answer Slack question",
                )

                say(
                    text=(
                        "I encountered an error while trying "
                        "to answer that question."
                    ),
                    thread_ts=thread_ts or ts,
                )

    def _run_reminder_worker(self) -> None:
        """
        Poll PostgreSQL for due reminders and deliver them via Slack DM.
        """

        while True:
            try:
                due_reminders = self._reminder_service.find_due()

                for reminder in due_reminders:
                    try:
                        dm_channel = self._slack_client.open_dm(
                            reminder.target_user_id,
                        )

                        self._slack_client.post_message(
                            channel=dm_channel,
                            text=f"Reminder: {reminder.task}",
                        )

                        sent_at = datetime.now(timezone.utc)

                        next_reminder_at = self._reminder_service.next_reminder_time(
                            now=sent_at,
                            timezone_name=self._settings.reminder_timezone,
                            time_1=self._settings.reminder_time_1,
                            time_2=self._settings.reminder_time_2,
                        )

                        self._reminder_service.mark_sent(
                            reminder,
                            last_sent_at=sent_at,
                            next_reminder_at=next_reminder_at,
                        )

                    except Exception:
                        logger.exception(
                            "Failed to deliver reminder %s",
                            reminder.graph_id,
                        )

            except Exception:
                logger.exception(
                    "Reminder worker iteration failed",
                )

            time.sleep(30)

    def start(self) -> None:
        reminder_worker = threading.Thread(
            target=self._run_reminder_worker,
            name="polis-reminder-worker",
            daemon=True,
        )
        reminder_worker.start()

        handler = SocketModeHandler(
            self._app,
            self._settings.slack_app_token,
        )
        handler.start()

if __name__ == "__main__":
    from slack_listener import create_listener

    listener = create_listener()
    listener.start()
