"""
Slack Socket Mode integration for POLIS.
"""

from __future__ import annotations

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

from infrastructure.config.settings import get_settings

from connectors.slack.models import (
    SlackEvent,
    SlackUser,
    SlackChannel,
    SlackMessage,
)

from connectors.slack.services import SlackService

from domain.reasoning import (
    Question,
)


class SlackSocketMode:
    """
    Slack Socket Mode listener.
    """

    def __init__(
        self,
        slack_service: SlackService,
    ) -> None:

        self._slack_service = slack_service
        self._settings = get_settings()

        self._app = App(
            token=self._settings.slack_bot_token,
        )

        self._register_handlers()

    def _register_handlers(self) -> None:

        @self._app.event("message")
        def handle_message(event, say, logger):

            # ======================================================
            # Ignore messages generated by bots.
            # ======================================================

            if event.get("bot_id"):
                return

            # ======================================================
            # Ignore Slack message subtypes.
            # ======================================================

            if event.get("subtype"):
                return

            user_id = event.get("user")
            channel_id = event.get("channel")
            text = event.get("text", "")
            ts = event.get("ts")
            thread_ts = event.get("thread_ts")

            if not user_id:
                return

            if not channel_id:
                return

            if not ts:
                return

            # ======================================================
            # Detect whether this message is directed at POLIS.
            # ======================================================

            bot_user_id = self._settings.slack_bot_user_id

            mention_token = f"<@{bot_user_id}>"

            is_polis_question = mention_token in text

            # ======================================================
            # Always ingest the message first.
            #
            # This preserves the existing learning pipeline.
            # ======================================================

            slack_event = SlackEvent(
                user=SlackUser(
                    user_id=user_id,
                ),
                channel=SlackChannel(
                    channel_id=channel_id,
                ),
                message=SlackMessage(
                    text=text,
                    ts=ts,
                    thread_ts=thread_ts,
                ),
            )

            try:

                saved = self._slack_service.ingest(
                    slack_event,
                )

                logger.info(
                    "POLIS processed Slack message: %s",
                    saved.correlation_id.business_id,
                )

            except Exception:

                logger.exception(
                    "POLIS failed to process Slack message",
                )

                return

            # ======================================================
            # If POLIS was not mentioned, learning is complete.
            # Do not reply.
            # ======================================================

            if not is_polis_question:
                return

            # ======================================================
            # Remove the POLIS mention from the question.
            # ======================================================

            question_text = text.replace(
                mention_token,
                "",
            ).strip()

            if not question_text:
                return

            # ======================================================
            # Ask the POLIS cognitive engine.
            # ======================================================

            try:

                question = Question(
                    text=question_text,
                )

                answer = self._slack_service.ask(
                question,
                )

                logger.info(
                    "POLIS answer confidence: %s",
                    answer.confidence,
                )

                # ==================================================
                # Reply in the same thread.
                #
                # If the original message is already in a thread,
                # use its parent thread_ts.
                #
                # Otherwise, the current message becomes the
                # thread parent.
                # ==================================================

                reply_thread_ts = (
                    thread_ts or ts
                )

                say(
                    text=answer.text,
                    thread_ts=reply_thread_ts,
                )

            except Exception:

                logger.exception(
                    "POLIS failed to answer Slack question",
                )

                say(
                    text=(
                        "I encountered an error while trying "
                        "to answer that question."
                    ),
                    thread_ts=thread_ts or ts,
                )

    def start(self) -> None:

        handler = SocketModeHandler(
            self._app,
            self._settings.slack_app_token,
        )

        handler.start()


if __name__ == "__main__":
    slack_service = SlackService()
    listener = SlackSocketMode(slack_service)
    listener.start()        