"""create knowledge base tables

Revision ID: 527f07685d62
Revises: 8a2f4d6c9e11
Create Date: 2026-09-24 15:02:38.329567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '527f07685d62'
down_revision: Union[str, Sequence[str], None] = '8a2f4d6c9e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_chunks_document_id'), 'knowledge_base_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_chunks_qdrant_point_id'), 'knowledge_base_chunks', ['qdrant_point_id'], unique=True)
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('object_key', sa.String(length=1000), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_documents_checksum'), 'knowledge_base_documents', ['checksum'], unique=True)
    op.create_index(op.f('ix_knowledge_base_documents_object_key'), 'knowledge_base_documents', ['object_key'], unique=True)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_documents_object_key'), table_name='knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_documents_checksum'), table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_chunks_qdrant_point_id'), table_name='knowledge_base_chunks')
    op.drop_index(op.f('ix_knowledge_base_chunks_document_id'), table_name='knowledge_base_chunks')
    op.drop_table('knowledge_base_chunks')
    # ### end Alembic commands ###
